user1 = User.create(username: 'user1')
user2 = User.create(username: 'user2')
user3 = User.create(username: 'user3')
user4 = User.create(username: 'user4')

product1 = Product.create(name: 'MP5', description: 'Short range weapon', owner: user1)
product2 = Product.create(name: 'AMW', description: 'Long range sniper', owner: user2)
product3 = Product.create(name: 'War Helmet', description: 'Adds extra protection for head', owner: user3)
product4 = Product.create(name: 'Grenade', description: 'Short area explosive grenade', owner: user4)
product5 = Product.create(name: 'M4A1', description: 'Long range weapon', owner: user1)
product6 = Product.create(name: 'CSGO Mansion', description: 'Popular video game Counter Strike map replica', owner: user1)
product7 = Product.create(name: 'Desert', description: 'Big desert full of obstacles and places to take cover', owner: user2)
product8 = Product.create(name: 'Haunted District', description: 'An empty mini city with old cars, houses and stores', owner: user1)

Reservation.create(user: user3, product: product1)
Reservation.create(user: user3, product: product2)
Reservation.create(user: user4, product: product3)
Reservation.create(user: user4, product: product4)
Reservation.create(user: user2, product: product5)
